function presentacion()
clear,clc,cla,close all
%Creamos figura
figure('Units','Pixels','Position',[0.0725  0.0725 1020 720],...
    'Numbertitle','off',...
    'Name','Estructuras I',...
    'Menubar','none',...
    'color',[0 0 0]);
%Ubicamos ejes en figura
axes('Units','Normalized','Position',[0 0 1 1]);
%Centrar figure
scrsz=get(0, 'ScreenSize');
pos_act=get(gcf,'Position');
xr=scrsz(3)-pos_act(3);
xp=round(xr/2);
yr=scrsz(4)-pos_act(4);
yp=round(yr/2);
set(gcf,'Position',[xp yp pos_act(3) pos_act(4)]);
%------------------------------------------------
%Include image
%Import image *.jpg, junto con su mapa de colores
[x,map]=imread('presentacion_img.jpg','jpg');
%Representamos  imagen en figura, con su mapa de colores
image(x),colormap(map),axis off,hold on

%Títulos sobre la imagen
%Título UTA
text(300,180,'UNIVERSIDAD TÉCNICA DE AMBATO','Fontname','Times New Roman',...
    'Fontsize',30,'Fontangle','Italic','Fontweight','Bold','background','black',...
    'color',[1 0 0]);
%Título
text(340,360,'Facultad de Ingeniería Civil y Mecánica','Fontname','Times New Roman',...
    'Fontsize',30,'Fontangle','Italic','Fontweight','Bold','background','black',...
    'color',[1 0 0]);
%Título
text(540,540,'Carrera de Ingeniería Civil','Fontname','Times New Roman',...
    'Fontsize',30,'Fontangle','Italic','Fontweight','Bold','background','black',...
    'color',[1 0 0]);
%Título
text(435,720,'PROGRAMA DE CELOSÍAS 2D','Fontname','Times New Roman',...
    'Fontsize',30,'Fontangle','Italic','Fontweight','Bold','background','black',...
    'color',[0.1 1 0.8]);
%Nombre del programador
text(600,1000,'Realizado por: Pablo Fernando Gallegos Díaz','Fontname','Comic Sans MS',...    'Fontsize',30,'Fontangle','Italic','Fontweight','Bold',...
    'Fontsize',15,'Fontangle','Italic','Fontweight','Bold',...
    'color',[1 0.5 0.5]); %Color en RBG

%Boton continuar: abre la GUI siguiente
botok=uicontrol('Style','pushbutton','Units','Normalized',...
    'Position',[.74 .03 .22 .09],...
    'String','CONTINUAR',...
    'Callback','clear all; close all; celosia;');
%Prog es el nombre del programa que se abrira